import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,ArrowUpRight,AudioLines,CheckCircle2,Download,FileAudio,FlaskConical,Headphones,Info,Play,Upload,ChevronRight,X} from 'lucide-react';
import {api,number} from './api';
import {Chart} from './components/Chart';
import {Benchmark} from './components/Benchmark';
import type {Series} from './components/Chart';
import type {Event,Features,Job,Recording,Reference,Result,Scores} from './types';
import './styles.css';

const names:Record<string,string>={pacing:'Pacing',pauses:'Pauses',intonation:'Intonation',energy:'Emphasis & energy',clarity:'Clarity',pace:'Pacing',recording_quality:'Recording quality'};
const defaultWeights={pacing:.25,pauses:.2,intonation:.25,energy:.2,clarity:.1};
function App(){
 const [tab,setTab]=useState('analysis'),[references,setReferences]=useState<Reference[]>([]),[records,setRecords]=useState<Recording[]>([]);
 const [referenceId,setReferenceId]=useState(''),[transcript,setTranscript]=useState(''),[referenceText,setReferenceText]=useState('');
 const [participantFile,setParticipantFile]=useState<File|null>(null),[referenceFile,setReferenceFile]=useState<File|null>(null),[confirmed,setConfirmed]=useState(false);
 const [preset,setPreset]=useState('persuasive_oratory'),[rubrics,setRubrics]=useState<Record<string,{name:string;weights:Record<string,number>}>>({}),[weights,setWeights]=useState<Record<string,number>>(defaultWeights);
 const [job,setJob]=useState<Job|null>(null),[jobId,setJobId]=useState<string|null>(localStorage.getItem('speechlens.job')),[result,setResult]=useState<Result|null>(null),[scores,setScores]=useState<Scores|null>(null);
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[healthy,setHealthy]=useState(false),[selected,setSelected]=useState<Event|null>(null),[filter,setFilter]=useState('all'),[minSeverity,setMinSeverity]=useState(1),[normalized,setNormalized]=useState(false);
 const [group,setGroup]=useState(''),[family,setFamily]=useState('pace'),[explorerSelection,setExplorerSelection]=useState(''),[rawPitch,setRawPitch]=useState(false);
 const participantAudio=useRef<HTMLAudioElement>(null),referenceAudio=useRef<HTMLAudioElement>(null);
 const endTimes=useRef<Record<string,number|null>>({});
 useEffect(()=>{api<Reference[]>('/api/references').then(setReferences).catch(e=>setError(e.message));api<Record<string,{name:string;weights:Record<string,number>}>>('/api/rubrics').then(setRubrics).catch(()=>{});api<{recordings:Recording[]}>('/api/dataset').then(d=>{setRecords(d.recordings);setGroup(d.recordings[0]?.pair_group_id||'');}).catch(()=>{});api<{worker_ready:boolean}>('/healthz').then(h=>setHealthy(h.worker_ready)).catch(()=>{});},[]);
 useEffect(()=>{if(!jobId)return;let alive=true;let timer:number;
  const poll=async()=>{try{const j=await api<Job>(`/api/evaluations/${jobId}`);if(!alive)return;setJob(j);
   if(j.status==='succeeded'){const r=await api<Result>(`/api/evaluations/${jobId}/result`);if(alive){setResult(r);setScores(r.scores);setPreset(r.scores.preset);setWeights(Object.fromEntries(Object.entries(r.scores.categories).map(([k,v])=>[k,v.weight])));setSelected(null);setBusy(false);}}
   else if(j.status==='failed'){setError(j.error||'Processing failed');setBusy(false);}
   else timer=window.setTimeout(poll,900);
  }catch(e){if(alive){setError((e as Error).message);setBusy(false);}}};poll();return()=>{alive=false;clearTimeout(timer);};},[jobId]);
 function acceptJob(j:Job){localStorage.setItem('speechlens.job',j.id);setJob(j);setJobId(j.id);setResult(null);setScores(null);setSelected(null);setBusy(true);setError('');setTab('analysis');}
 async function demo(id?:string){setBusy(true);try{acceptJob(await api<Job>(`/api/demo${id?'?recording_id='+encodeURIComponent(id):''}`,{method:'POST'}));}catch(e){setError((e as Error).message);setBusy(false);}}
 async function submit(e:React.FormEvent){e.preventDefault();if(!participantFile)return;setError('');setBusy(true);const data=new FormData();data.set('participant',participantFile);data.set('transcript',transcript);data.set('preset',preset);data.set('weights',JSON.stringify(weights));data.set('single_speaker',String(confirmed));data.set('language','en');
  if(referenceId&&referenceId!=='upload')data.set('reference_id',referenceId);
  if(referenceId==='upload'&&referenceFile){data.set('reference',referenceFile);data.set('reference_text',referenceText);}
  try{acceptJob(await api<Job>('/api/evaluations',{method:'POST',body:data}));}catch(e){setError((e as Error).message);setBusy(false);}}
 async function changePreset(value:string){setPreset(value);const w=rubrics[value]?.weights||defaultWeights;setWeights(w);if(result&&jobId){try{setScores(await api<Scores>(`/api/evaluations/${jobId}/rescore`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({preset:value,weights:w})}));setResult(await api<Result>(`/api/evaluations/${jobId}/result`));}catch(e){setError((e as Error).message);}}}
 async function applyWeights(){if(result&&jobId){try{setScores(await api<Scores>(`/api/evaluations/${jobId}/rescore`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({preset,weights})}));setResult(await api<Result>(`/api/evaluations/${jobId}/result`));}catch(e){setError((e as Error).message);}}}
 function seek(role:string,t:number,end:number|null=null,play=false){const player=role==='participant'?participantAudio.current:referenceAudio.current;const other=role==='participant'?referenceAudio.current:participantAudio.current;other?.pause();if(player){player.currentTime=t;endTimes.current[role]=end;if(play)player.play().catch(e=>setError(e.message));}}
 function selectEvent(e:Event){setSelected(e);seek('participant',e.participant_interval_s[0]);if(e.reference_interval_s)seek('reference',e.reference_interval_s[0]);}
 const displayed=result?.events.filter(e=>(filter==='all'||e.type===filter)&&e.severity_level>=minSeverity)||[];
 const roles=result?Object.keys(result.features):[];
 function series(key:'pitch'|'energy'|'waveform'):Series[]{return roles.flatMap(role=>{const f=result!.features[role];const base={role,words:result!.alignments[role].words,times:key==='pitch'?f.pitch.time_s:key==='energy'?f.spectral.time_s:f.waveform.time_s,values:key==='pitch'?(rawPitch?f.pitch.f0_hz:f.pitch.semitones):key==='energy'?f.spectral.energy_relative_db:f.waveform.max};return key==='waveform'?[{...base,id:role+'max'},{...base,id:role+'min',values:f.waveform.min}]:[base];});}
 const explorerRows=records.filter(r=>r.pair_group_id===group&&(r.flaw_family===family||r.flaw_family==='accepted'||(family==='controls'&&(r.flaw_family.startsWith('accepted_')||r.flaw_family.startsWith('sham_')))));
 const exploreRecord=records.find(r=>r.recording_id===explorerSelection)||explorerRows[0];
 return <div className="app">
  <aside className="sidebar"><a className="brand" href="/" aria-label="SpeechLens home"><span className="brand-icon"><AudioLines size={25}/></span>SpeechLens<span className="brand-dot">.</span></a><div className="workspace-label">RESEARCH WORKSPACE</div><nav aria-label="Main navigation">
   <button className={tab==='analysis'?'active':''} onClick={()=>setTab('analysis')}><Activity size={18}/>Speech analysis<ChevronRight size={14}/></button>
   <button className={tab==='dataset'?'active':''} onClick={()=>setTab('dataset')}><FlaskConical size={18}/>Dataset explorer</button>
   <button className={tab==='method'?'active':''} onClick={()=>setTab('method')}><Info size={18}/>Method & provenance</button>
  </nav><div className="sidebar-footer"><div className="status-line"><span className={healthy?'status-dot':'status-dot offline'}/>{healthy?'CPU worker ready':'Worker unavailable'}</div><p>English · single speaker<br/>Local processing · v0.1.0</p><span className="prototype">RESEARCH PROTOTYPE</span></div></aside>
  <main><header className="topbar"><span>Workspace <ChevronRight size={13}/> {tab==='dataset'?'Dataset explorer':tab==='method'?'Method & provenance':'Speech analysis'}</span><span className="privacy"><CheckCircle2 size={14}/>Uploads stay local</span></header>
  {error&&<div role="alert" className="error"><strong>Action needed</strong><span>{error}</span><button aria-label="Dismiss error" onClick={()=>setError('')}><X size={17}/></button>{job?.status==='failed'&&<button onClick={async()=>{try{acceptJob(await api<Job>(`/api/evaluations/${job.id}/retry`,{method:'POST'}));}catch(e){setError((e as Error).message);}}}>Retry processing</button>}</div>}
  {tab==='analysis'&&<><section className="page-heading"><div><div className="eyebrow">CONTRASTIVE SPEECH ANALYTICS</div><h1>Hear the difference.<br/><span>See the evidence.</span></h1><p>Compare the same words, discover delivery differences,<br className="desktop"/> and trace every finding to a moment in the audio.</p></div><button className="secondary demo-button" onClick={()=>demo()} disabled={busy}><Play size={15}/>Process demo pair<ArrowUpRight size={14}/></button></section>
   <div className="workflow"><span className="step"><b>01</b> Choose audio</span><ChevronRight size={14}/><span className="step"><b>02</b> Compare delivery</span><ChevronRight size={14}/><span className="step"><b>03</b> Explore evidence</span></div>
   <form onSubmit={submit} className="panel upload-panel"><div className="section-heading"><div><h2>Start a comparison</h2><p>The same transcript. Two independent performances.</p></div><span className="badge">{referenceId?'PAIRED EVALUATION':'UNPAIRED DIAGNOSTICS'}</span></div>
    <div className="upload-grid"><div><label htmlFor="reference-select">01 / REFERENCE DELIVERY</label><select id="reference-select" value={referenceId} onChange={e=>{setReferenceId(e.target.value);const r=references.find(r=>r.id===e.target.value);if(r)setTranscript(r.transcript);}}><option value="">No reference — diagnostics only</option>{references.map(r=><option key={r.id} value={r.id}>{r.title} · {number(r.duration_s)}s · review pending</option>)}<option value="upload">Upload my own reference</option></select>
     {referenceId==='upload'?<><label className="file-drop"><FileAudio size={26}/><span>{referenceFile?.name||'Choose reference audio'}</span><input aria-label="Reference audio" type="file" accept="audio/*,.mp4,.webm" onChange={e=>setReferenceFile(e.target.files?.[0]||null)}/></label><label htmlFor="reference-text">Corrected reference transcript</label><textarea id="reference-text" required value={referenceText} onChange={e=>setReferenceText(e.target.value)}/></>:<div className="reference-note"><Headphones size={22}/><p>{referenceId?'A public-source rendition with recorded provenance. Independent human quality review is pending.':'A reference enables text-matched delivery scores. Without one, measurements remain diagnostics.'}</p></div>}</div>
     <div><label>02 / PARTICIPANT DELIVERY</label><label className="file-drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();setParticipantFile(e.dataTransfer.files[0]||null);}}><Upload size={27}/><strong>{participantFile?.name||'Drop your recording here'}</strong><span>{participantFile?'Ready to process':'or browse files · up to 100 MB / 10 minutes'}</span><input aria-label="Participant audio" type="file" accept="audio/*,.mp4,.webm" required={!participantFile} onChange={e=>setParticipantFile(e.target.files?.[0]||null)}/></label></div></div>
    <label htmlFor="transcript" className="transcript-label">03 / CONFIRM THE INTENDED TRANSCRIPT <span>Every word matters for alignment</span></label><textarea id="transcript" placeholder="Paste the exact intended words, including repetitions. In paired mode the canonical text must match the reference." value={transcript} onChange={e=>setTranscript(e.target.value)} required/>
    <div className="form-bottom"><label className="checkbox"><input type="checkbox" checked={confirmed} required onChange={e=>setConfirmed(e.target.checked)}/>I confirm this is English, single-speaker speech.</label><button className="primary" disabled={busy||!participantFile||!confirmed} type="submit">{busy?'Processing…':'Analyze delivery'}<ArrowUpRight size={16}/></button></div>
   </form>
   {job&&<section className="panel job" aria-live="polite"><span className="status-dot"/><strong>{job.stage}</strong><span>{job.status} · attempt {job.attempts}</span><progress aria-label="Processing progress" value={job.progress} max={1}/></section>}
   {result&&scores&&<div className="results" data-testid="results"><div className="result-heading"><div><div className="eyebrow">YOUR ANALYSIS</div><h2>Delivery, made visible.</h2><p>{result.mode==='paired'?'Text-matched comparison':'Unpaired observations'} · {number(result.provenance.processing_s)}s CPU processing · {result.provenance.cache_hit?'hash-matched cache':'fresh inference'}</p></div><div className="export-controls"><a className="secondary" href={`/api/evaluations/${jobId}/export?format=json`} download><Download size={15}/>Evidence JSON</a><a className="secondary" href={`/api/evaluations/${jobId}/export`} download>JSON + CSV</a></div></div>
    <div className="notice"><Info size={17}/><span>Experimental comparisons with uncalibrated thresholds. A reference is one acceptable delivery; a stylistic difference needs review.</span></div>
    <div className="score-grid"><div className="score-total panel"><span>DELIVERY SCORE</span><div>{scores.total==null?'—':number(scores.total)}<small>/ 100</small></div><p>{scores.total==null?'Insufficient evidence for an overall score':'Experimental paired score'}</p><span>Coverage {number(scores.coverage*100)}%</span></div>{Object.entries(scores.categories).map(([k,v])=><div className="score-card panel" key={k}><span>{names[k]}</span><strong>{v.score==null?'—':number(v.score)}</strong><div className="score-meter"><span style={{width:`${v.score||0}%`}}/></div><p>{v.score==null?v.status.replaceAll('_',' '):`${number(v.coverage*100,0)}% evidence coverage`}</p><span>Included weight {number((scores.included_weights[k]||0)*100,0)}%</span></div>)}</div>
    <details className="panel rubric"><summary>Rubric settings · {rubrics[preset]?.name||preset} · clarity diagnostic-only</summary><div className="rubric-controls"><label>Genre preset<select aria-label="Genre preset" value={preset} onChange={e=>changePreset(e.target.value)}>{Object.entries(rubrics).map(([k,v])=><option key={k} value={k}>{v.name}</option>)}</select></label>{Object.entries(weights).map(([k,v])=><label key={k}>{names[k]}<input aria-label={`${names[k]} weight`} type="number" min="0" max="1" step=".05" value={v} onChange={e=>setWeights({...weights,[k]:Number(e.target.value)})}/></label>)}<button className="secondary" type="button" onClick={applyWeights}>Apply weights</button></div><p>{scores.clarity_note}</p></details>
    <section className="panel acoustic-panel"><div className="section-heading"><div><h2>Acoustic evidence</h2><p>Relative measures keep your natural voice. Timing stays native.</p></div><div className="view-toggle" role="group" aria-label="Chart coordinate system"><button className={!normalized?'chosen':''} onClick={()=>setNormalized(false)}>Native time</button><button className={normalized?'chosen':''} onClick={()=>setNormalized(true)}>Token comparison</button></div></div><div className="legend"><span><i className="participant-key"/>Participant</span>{result.mode==='paired'&&<span><i className="reference-key"/>Reference · dashed</span>}</div>
     <div className="audio-grid">{roles.map(role=><div key={role}><label>{role.toUpperCase()} · {number(result.features[role].duration_s)}s</label><audio ref={role==='participant'?participantAudio:referenceAudio} controls preload="metadata" src={`/api/evaluations/${jobId}/audio/${role}`} onTimeUpdate={e=>{const end=endTimes.current[role];if(end!=null&&e.currentTarget.currentTime>=end){e.currentTarget.pause();endTimes.current[role]=null;}}} aria-label={`${role} audio`}/></div>)}</div>
     <Chart title="Waveform peak envelope" unit="digital amplitude" series={series('waveform')} normalized={normalized} selection={selected?.participant_interval_s} onSeek={t=>seek('participant',t)}/><label className="checkbox" style={{marginTop:20}}><input type="checkbox" checked={rawPitch} onChange={e=>setRawPitch(e.target.checked)}/>Show raw F0 in Hertz (normalized semitones are used for scoring)</label><Chart title="Pitch contour" unit={rawPitch?"Hertz":"semitones relative to recording median"} series={series('pitch')} normalized={normalized} selection={selected?.participant_interval_s} onSeek={t=>seek('participant',t)}/><Chart title="Relative energy" unit="dB relative to median speech energy" series={series('energy')} normalized={normalized} selection={selected?.participant_interval_s} onSeek={t=>seek('participant',t)}/>
     <Chart title="Phrase pacing" unit="words / minute (elapsed duration)" normalized={normalized} series={roles.map(role=>({role,showPoints:true,tokenXs:result.comparison.phrases.filter(p=>p[role as 'participant'|'reference']?.interval_s).map(p=>p.token_ids.reduce((a,b)=>a+b,0)/p.token_ids.length+.5),words:result.alignments[role].words,times:result.comparison.phrases.filter(p=>p[role as 'participant'|'reference']?.interval_s).map(p=>{const u=p[role as 'participant'|'reference']!;return (u.interval_s![0]+u.interval_s![1])/2;}),values:result.comparison.phrases.filter(p=>p[role as 'participant'|'reference']?.interval_s).map(p=>p[role as 'participant'|'reference']?.wpm||null)}))}/>
     <details><summary>Native pause boundaries · seconds, confirmed with speech VAD</summary><div className="pause-table"><table><thead><tr><th>After word</th><th>Participant gap</th><th>Reference gap</th></tr></thead><tbody>{result.comparison.boundaries.map(b=><tr key={b.id}><td>{result.transcript.tokens[b.id].text}</td><td>{number(b.participant?.pause_s,2)}</td><td>{number(b.reference?.pause_s,2)}</td></tr>)}</tbody></table></div></details>
    </section>
    <div className="evidence-grid"><section className="panel findings"><div className="section-heading"><div><h2>Grounded findings <span className="count">{result.events.length}</span></h2><p>Predictions on the participant’s actual clock.</p></div></div><div className="filters"><select aria-label="Filter findings" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All types</option>{[...new Set(result.events.map(e=>e.type))].map(t=><option key={t} value={t}>{names[t]||t}</option>)}</select><select aria-label="Minimum severity" value={minSeverity} onChange={e=>setMinSeverity(Number(e.target.value))}>{[1,2,3,4].map(s=><option key={s} value={s}>Level {s}+</option>)}</select></div><div className="event-timeline" aria-label="Finding timeline">{displayed.map(e=><button key={e.id} aria-label={`${names[e.type]||e.type} at ${number(e.participant_interval_s[0])} seconds`} style={{left:`${e.participant_interval_s[0]/result.features.participant.duration_s*100}%`,width:`${Math.max(1,(e.participant_interval_s[1]-e.participant_interval_s[0])/result.features.participant.duration_s*100)}%`}} onClick={()=>selectEvent(e)}>{e.severity_level}</button>)}</div>
     {displayed.length?displayed.map(e=><button className={`event-row ${selected?.id===e.id?'selected':''}`} data-testid="event-row" key={e.id} onClick={()=>selectEvent(e)}><span className="event-level">L{e.severity_level}</span><span><strong>{names[e.type]||e.type}</strong><small>{number(e.participant_interval_s[0],2)}–{number(e.participant_interval_s[1],2)}s · {e.quote}</small></span><ChevronRight size={16}/></button>):<div className="empty-findings"><CheckCircle2 size={24}/><p>No supported findings in this filter.</p><small>Absence of findings does not establish effective delivery when evidence is missing.</small></div>}
    </section><section className="panel explanation"><div className="eyebrow">EVIDENCE DRAWER</div>{selected?<><h2>{names[selected.type]||selected.type}</h2><blockquote>“{selected.quote||'Recording quality'}”</blockquote><div className="measurement-grid"><div><span>Participant</span><strong>{typeof selected.measurements.participant==='number'?number(selected.measurements.participant,2):'—'}</strong></div><div><span>Reference</span><strong>{typeof selected.measurements.reference==='number'?number(selected.measurements.reference,2):'—'}</strong></div></div><p className="measurement-unit">{selected.measurements.units} · {selected.type==='pace'?'log duration ratio (dimensionless)':'delta'} {number(selected.delta,3)}</p><p>{selected.interpretation}</p><div className="coaching"><span>TRY THIS</span><p>{selected.suggestion}</p></div><div className="ab-buttons"><button className="primary" onClick={()=>seek('participant',selected.participant_interval_s[0],selected.participant_interval_s[1],true)}><Play size={14}/>Play participant span</button>{selected.reference_interval_s&&<button className="secondary" onClick={()=>seek('reference',selected.reference_interval_s![0],selected.reference_interval_s![1],true)}><Headphones size={14}/>Play reference span</button>}</div><details><summary>Rule, thresholds & confidence</summary><code>{selected.rule_id}</code><p>{selected.formula}</p><pre>{JSON.stringify(selected.thresholds,null,2)}</pre><p>{selected.confidence_rationale}</p><small>Boundary uncertainty: ±0.1s heuristic, not reviewed accuracy.</small></details></>:<div className="drawer-empty"><AudioLines size={38}/><h3>Follow the evidence.</h3><p>Select a finding to compare measured values, listen to matching spans, and explore the rule.</p></div>}</section></div>
    <section className="panel transcript-panel"><div className="section-heading"><div><h2>Aligned transcript</h2><p>Click a word to seek. Underlined words have no reliable alignment.</p></div><span className="badge">{number(result.alignments.participant.coverage*100)}% ALIGNED</span></div><div className="tokens">{result.transcript.tokens.map(t=>{const word=result.alignments.participant.words[t.id];return <button key={t.id} disabled={word.start_s===null} className={`${word.start_s===null?'unaligned':''} ${selected?.token_ids.includes(t.id)?'highlighted':''}`} title={word.start_s===null?'Unaligned — insufficient evidence':`${number(word.start_s,2)}s · confidence heuristic ${number(word.confidence,2)}`} onClick={()=>seek('participant',word.start_s!)}>{t.text}</button>;})}</div></section>
    <details className="panel warnings"><summary>Uncertainty & processing provenance ({result.warnings.length})</summary><ul>{result.warnings.map(w=><li key={w}>{w}</li>)}</ul><pre>{JSON.stringify(result.provenance,null,2)}</pre><button className="secondary" onClick={async()=>{if(jobId){try{await api(`/api/evaluations/${jobId}`,{method:'DELETE'});localStorage.removeItem('speechlens.job');setJobId(null);setResult(null);setJob(null);}catch(e){setError((e as Error).message);}}}}>Delete this evaluation and its uploads</button></details>
   </div>}
   {!result&&!busy&&<div className="principles"><div><span>01 / SAME WORDS</span><p>Hold the text constant.<br/>Compare the performance.</p></div><div><span>02 / NATIVE TIME</span><p>Every finding points to<br/>the actual recording.</p></div><div><span>03 / MEASURED EVIDENCE</span><p>Numbers, context, and<br/>a next rehearsal action.</p></div></div>}
  </>}
  {tab==='dataset'&&<><section className="page-heading"><div><div className="eyebrow">CONTROLLED CONTRASTS</div><h1>One text.<br/><span>A spectrum of delivery.</span></h1><p>{records.length} real recordings. Explore generated interventions and measured outputs.</p></div></section><div className="notice"><Info size={18}/><span>Levels describe injected transformations. They are not independent human ratings. Support intervals and perceptual ground truth are separate.</span></div><section className="panel explorer"><div className="filters"><label>Source excerpt<select aria-label="Source excerpt" value={group} onChange={e=>{setGroup(e.target.value);setExplorerSelection('');}}>{[...new Set(records.map(r=>r.pair_group_id))].map(g=><option key={g}>{g}</option>)}</select></label><label>Flaw family<select aria-label="Flaw family" value={family} onChange={e=>{setFamily(e.target.value);setExplorerSelection('');}}>{['pace','intonation','pauses','energy','clarity_proxy','controls'].map(f=><option key={f}>{f}</option>)}</select></label></div><div className="level-grid">{explorerRows.map(r=><button key={r.recording_id} data-testid={'record-'+r.recording_id} className={`level-card ${exploreRecord?.recording_id===r.recording_id?'selected':''}`} onClick={()=>setExplorerSelection(r.recording_id)}><span>LEVEL {r.severity_label}</span>{family==='controls'&&<p>{r.flaw_family.replaceAll('_',' ')}</p>}<strong>{r.measured?.score==null?'—':number(r.measured.score)}</strong><small>Measured delivery score</small><p>{number(r.duration_s)}s · {r.split}</p><small>{r.measured?`${r.measured.events} predicted events`:'Not evaluated yet'}</small></button>)}</div>{exploreRecord&&<div className="explorer-playback"><label>{exploreRecord.recording_id}</label><audio controls src={`/api/dataset/${exploreRecord.recording_id}/audio`} aria-label="Dataset recording audio"/><p>Review status: {exploreRecord.review_status}. Recording degradation proxies do not prove poor articulation.</p><button className="primary" disabled={busy} onClick={()=>demo(exploreRecord.recording_id)}><Play size={15}/>Process this recording</button></div>}</section></>}
  {tab==='method'&&<><section className="page-heading"><div><div className="eyebrow">REPRODUCIBLE BY DESIGN</div><h1>Evidence before<br/><span>interpretation.</span></h1><p>What this prototype measures, and where it abstains.</p></div></section><section className="panel method"><h2>A deterministic, modular pipeline</h2><p>Validate audio → canonicalize intended text → independently align each recording → extract native-time features → match token and phrase IDs → detect → score → explain.</p><h3>Speaker normalization</h3><p>Pitch = 12 log₂(F0 / recording median F0). Energy = dBFS − median speech dBFS. Neither is divided by its own range: expressiveness remains measurable. All pace and pause measurements retain actual elapsed time.</p><h3>Scoring and abstention</h3><p>Category penalty = Σ eligible exposure × severity / Σ eligible exposure. Overlapping evidence in the same scoring unit uses the maximum. Missing evidence produces null category scores. Coverage below 60% withholds the total. Clarity is diagnostic-only and remaining weights are renormalized.</p><h3>Alignment and quality limits</h3><p>Pinned English Wav2Vec2 CTC model with supplied-text Viterbi alignment and ASR edit matching. Independent WebRTC VAD includes unvoiced speech. Historical channel noise, omitted words, overlapping voices, severe clipping and weak pitch support can trigger abstention.</p><h3>Dataset provenance and review</h3><p>Public source pages, original checksums, crop clocks and transcript provenance live in data/provenance. All generated support labels are disclosed as synthetic; independent human reviews and consenting human renditions remain pending. All related source/speaker/text recordings stay in a single split.</p><h3>Local privacy</h3><p>Uploaded recordings live in the configured local storage volume. Use Delete evaluation to remove uploads and derived job artifacts. No upload is automatically added to the public dataset. This prototype is designed for trusted local use; do not expose it publicly without authentication.</p><h3>Submission status</h3><p>The repository includes the local dashboard, release data, measured evaluation and technical documentation. GitHub and YouTube publication, independent human annotation, and the original organizer PDF remain external submission gates. See BLOCKERS.md for current evidence.</p><Benchmark/></section></>}
  <footer>SpeechLens <span>Contrastive speech analytics & temporal flaw grounding</span><span>Measured. Traceable. Experimental.</span></footer>
  </main>
 </div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
